<template>
     <div>
        <section class="abp second-section">
            <div class="container">
                <div class="section-content">
                    <div class="row">
                        <h2>Privacy Policy</h2>
                        <hr>
                        <div class="about-content mt-10">
                           <p>We may collect and store information about you in connection with your use of the Service, including any information you transmit to or through the Service. We use that information to provide the Service’s functionality, fulfill your requests, improve the Service’s quality, engage in research and analysis relating to the Service, personalize your experience, track usage of the Service, provide feedback to third party businesses that are listed on the Service, display relevant advertising, market the Service, provide customer support, message you, back up our systems, allow for disaster recovery, enhance the security of the Service, and comply with legal obligations. Even when we do not retain such information, it still must be transmitted to our servers initially and stored long enough to process.

Please also note:

Account Information: If you create a Flank account, we may store and use the information you provide during that process, such as your full name, email address, zip code, physical address, and other information you may provide with your account, such as your gender, phone number, and birth date. We may publicly display your first name and last initial, as well as any photo or other content you submit through the registration process, as part of your account profile. You can modify some of the information associated with your account through your account settings. If you believe that someone has created an unauthorized account depicting you or your likeness, you can request its removal by flagging it.

Public Content: Your contributions to the Service are intended for public consumption and are therefore viewable by the public, including your photos, ratings, reviews, tips, lists, Collections, compliments, Ask the Community posts, Flank Talk posts, and edits to business listing information. Your account profile (e.g., first name, last initial, city, neighborhood, month and year joined, profile photos and friends) is also intended for public consumption, as is some of your other activity through the Service, like how you vote on other people’s contributions (e.g., useful, funny, cool, helpful, not helpful), which contributions you like, where you check-in or where your friends check-in on your behalf, which contributions or users you follow, and which businesses you bookmark. You can limit the public nature of some of these activities through your account settings.

Contacts: You can invite others to join or become your friend on Flank by providing us with their contact information, or by allowing us to access your contacts from your computer, mobile device, or third party sites to select which individuals you want to invite. If you allow us to access your contacts, we may transmit that information to our servers long enough to process your invitations.

Communications: When you sign up for an account or use certain features, you are opting to receive messages from other users, businesses, and Flank. You can manage some of your messaging preferences through your account settings, but note that you cannot opt out of receiving certain administrative, transactional, or legal messages from Flank. For example, if you make a reservation, order food, place yourself on a waitlist, or request a quote from a business through the Service, we may send you messages about your transaction using the contact information you provide, including through automated SMS text messages to your phone number. We may also track your actions in response to the messages you receive from us or through the Service, such as whether you deleted, opened, or forwarded such messages. If you exchange messages with others through the Service, we may store them in order to process and deliver them, allow you to manage them, and we may review and disclose them in connection with investigations related to use of the Service, as well as our efforts to improve the Service. We may not deliver messages that we believe are objectionable, such as spam messages, fraudulent solicitations, or requests to exchange reviews for compensation. If you send or receive messages through the Service via SMS text message, we may log phone numbers, phone carriers, and the date and time that the messages were processed. Carriers may charge recipients for texts that they receive. We may also store information that you provide through communications to us, including from phone calls, letters, emails and other electronic messages, or in person. If you are a representative of a business listed on Flank, we may contact you, including by phone or email, using the contact information you provide us, make publicly available, or that we have on record for your business. Our calls with you may be monitored and recorded for quality purposes.

Transactions: If you initiate a transaction through the Service, such as a reservation or purchase, we may collect and store information about you, such as your name, phone number, address, email, and payment information (such as a credit card number and expiration date), as well as any other information you provide to us, in order to process your transaction, send communications about them to you, and populate forms for future transactions. This information may be shared with third parties, and third parties may share such information with us, for the same purposes. When you submit credit card numbers, we encrypt that information using industry standard technology. If you write reviews about businesses with which you transact through the Service, we may publicly display the fact that you transacted with those businesses. For example, if you make a dinner reservation through the Service and write a review about your experience, we may publicly display the fact that you made your dinner reservation through the Service.

Activity: We may store information about your use of the Service, such as your search activity, the pages you view, the date and time of your visit, businesses you call using our mobile applications, and reservations, purchases, or transactions you make through the Service. We may also store information that your computer or mobile device may provide to us in connection with your use of the Service, such as your browser type, type of computer or mobile device, browser language, IP address, WiFi information such as SSID, mobile carrier, phone number, unique device identifier, advertising identifier, location (including geolocation, beacon based location, and GPS location), and requested and referring URLs and mobile applications. We may also receive and store your location whenever our mobile applications are running, including when running in the background, if you enable our mobile apps to access such information in the course of using the Service. You may be able to limit or disallow our use of certain location data through your device or browser settings, for example by adjusting the "Location Services" settings for our applications in iOS privacy settings.

Different Devices: You may access the Service through different devices (e.g., your mobile phone or personal computer) and different platforms (e.g., the Flank website or Flank mobile apps). The information that we collect and store through those different uses may be cross-referenced and combined, and your contributions through one Flank platform will typically be similarly visible and accessible through all other Flank platforms.

Legal Basis for Processing: For residents of the EEA and Switzerland only, our legal basis for collecting and using the information described above will depend on the specific information concerned and the context in which we collect it. We, however, will normally collect personal information from you only where we have your consent to do so, where we need the personal information to perform a contract with you, or where the processing is in our legitimate interests and not overridden by your data protection interests or fundamental rights and freedoms. In some cases, we may also have a legal obligation to collect personal information from you or may otherwise need the personal information to protect your vital interests or those of another person (for instance, to prevent, investigate, or identify possible wrongdoing in connection with the Service or to comply with legal obligations). If we ask you to provide personal information to comply with a legal requirement or to perform a contract with you, we will make this clear at the relevant time and advise you whether the provision of your personal information is mandatory or not (as well as of the possible consequences if you do not provide your personal information). If we collect and use your personal information in reliance on our legitimate interests (or those of any third party), this interest will typically be to operate our Services, communicate with you in relation to our Services, or for our other legitimate commercial interests, for instance, when responding to your queries, to analyze and improve our platform, engage in marketing, or for the purposes of detecting or preventing fraud. If you have questions about or need further information concerning the legal basis on which we collect and use your personal information, please contact us at the address listed below in the “Contact” section.</p>
                        </div>
                        
                    </div>
                </div>
            </div>
        </section>
    </div>
</template>

<script>
export default {

}
</script>

<style>

</style>
